# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
xcodeproj 'SMBeacon.xcodeproj'

target 'SMBeacon' do
    pod 'AFNetworking', '~> 2.2'
    pod 'Haneke', '~> 1.0'
end

target 'SMBeaconTests' do

end

